# Preface {.unnumbered}

This book was largely adapted from the public domain resource *Online Statistics Education: A Multimedia Course of Study* (<http://onlinestatbook.com/> Project Leader: David M. Lane, Rice University).

A huge thanks to David Lane and his colleagues at Rice University for their creation of this wonderful resource. I use footnotes throughout to indicate precisely where various sections of each chapter came from.

Chapters 11-13 (and section 4.4) were written by me (Nathan).

There are still formatting inconsistencies, and this is ever a work in progress. If you find errors, feel free to email me (favero\[at\]american\[dot\]edu) so I can correct them for the next version I publish.

## What's Unique About This Text?

1.  I introduce regression very early on (Ch. 3) so that students (especially PhD students) can quickly get started on their term papers and better understand any quantitative articles they're reading.

2.  I skip a traditional treatment of probability theory because I don't find traditional treatments to be very useful for students interested in applied statistics. Instead, I've written a chapter (11) on the logic and practice of building models that account for uncertainty.

## Past Versions

This version (1.3) was updated July 18, 2024.

Versions 1.1 and 1.2 are available at <https://nathanfavero.com/teaching-tools/>.

-   Version 1.3 updates: Various formatting updates. New section (4.4) on interpretting confidence intervals.

-   Version 1.2 updates: The discussion of transforming variables now appears in Ch. 2 (rather than Ch. 3).
